'use client';

import React, { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Shield, Lock, Unlock, FileText, Zap, Key, CheckCircle, RefreshCw, Copy, Download, FileJson, FileCode, FileType } from 'lucide-react';
import { cn } from '@/lib/utils';

// Specific file list from spec
const SAMPLE_FILES = [
    {
        id: '1',
        name: 'confidential-report.txt',
        type: 'text/plain',
        origSize: '1,247 bytes',
        encSize: '1,264 bytes',
        content: `CONFIDENTIAL REPORT
══════════════════

This is a sample encrypted document
demonstrating:
- AES-256-GCM encryption
- RSA-4096-OAEP key wrapping
- HMAC-SHA512 authentication
- Secure cloud storage

The content of this file is encrypted
client-side before upload. Even the cloud
provider cannot read this data!

Security Features:
✓ End-to-end encryption
✓ Zero-knowledge architecture
✓ Tamper-proof audit logs
✓ Quantum-resistant options

Generated by CryptoVault Enterprise
${new Date().toISOString()}`
    },
    {
        id: '2',
        name: 'medical-records.json',
        type: 'application/json',
        origSize: '856 bytes',
        encSize: '880 bytes',
        isJson: true,
        content: `{
  "patient": {
    "id": "PATIENT-12345",
    "name": "John Doe",
    "dob": "1990-01-01",
    "bloodType": "A+"
  },
  "diagnosis": [
    {
      "date": "2025-01-01",
      "condition": "Hypertension",
      "severity": "Mild"
    },
    {
      "date": "2025-06-15",
      "condition": "Type 2 Diabetes",
      "severity": "Controlled"
    }
  ],
  "medications": [
    {
      "name": "Lisinopril",
      "dosage": "10mg",
      "frequency": "Daily"
    }
  ],
  "encrypted": true,
  "encryptionAlgorithm": "AES-256-GCM",
  "note": "This sensitive medical data is protected by military-grade encryption"
}`
    },
    {
        id: '3',
        name: 'financial-data.csv',
        type: 'text/csv',
        origSize: '2.4 KB',
        encSize: '2.45 KB',
        content: `TransactionID,Date,Amount,Recipient,Status
TX-98765,2025-12-31,$5000.00,Vendor A,Cleared
TX-98766,2026-01-02,$1250.50,Service B,Pending
TX-98767,2026-01-05,$99.99,Utility C,Cleared
`
    },
    {
        id: '4',
        name: 'research-notes.md',
        type: 'text/markdown',
        origSize: '4.1 KB',
        encSize: '4.2 KB',
        content: `# Project Alpha Research Notes

## Quantum Resistance
Implementing CRYSTALS-Kyber for KEM.

## Zero Knowledge Proofs
Using Schnorr protocol for authentication without password transmission.
`
    }
];

export default function DemoPage() {
    // Generation State
    const [genState, setGenState] = useState<'idle' | 'generating' | 'generated'>('idle');
    const [genStep, setGenStep] = useState('');
    const [genProgress, setGenProgress] = useState(0);
    const [genLogs, setGenLogs] = useState<string[]>([]);

    // Decryption State
    const [decryptingIds, setDecryptingIds] = useState<Record<string, boolean>>({});
    const [decryptedIds, setDecryptedIds] = useState<Record<string, boolean>>({});
    const [decryptSteps, setDecryptSteps] = useState<Record<string, string>>({});
    const [decryptProgress, setDecryptProgress] = useState<Record<string, number>>({});

    const addGenLog = (log: string) => setGenLogs(prev => [...prev, log]);

    const handleGenerate = async () => {
        setGenState('generating');
        setGenProgress(0);
        setGenLogs([]);

        // State 2 - Key Generation (0-2300ms)
        setGenStep('Generating RSA-4096 key pair...');
        addGenLog('⏳ Generating RSA-4096 key pair...');

        // Simulate progress bar for 2.3s
        for (let i = 0; i <= 100; i += 5) {
            setGenProgress(i);
            await new Promise(r => setTimeout(r, 115)); // 2300ms total
        }
        addGenLog('✓ RSA-4096 key pair generated (2.3 seconds)');

        // State 3 - Encrypting Files (2300-3200ms)
        setGenStep('Encrypting sample files...');
        setGenProgress(0); // Reset for next phase or continue? Spec says "25%... 75%". I'll reset visually or handle specific file logs.

        for (const file of SAMPLE_FILES) {
            addGenLog(`⏳ Encrypting: ${file.name}...`);
            await new Promise(r => setTimeout(r, 200));
            addGenLog(`✓ Encrypted: ${file.name}`);
        }

        // State 5 - Complete
        setGenStep('All Files Encrypted Successfully!');
        setGenProgress(100);
        addGenLog('✓ 4 files encrypted with AES-256-GCM');
        addGenLog('✓ Keys wrapped with RSA-4096-OAEP');
        setGenState('generated');
    };

    const handleDecrypt = async (id: string) => {
        setDecryptingIds(prev => ({ ...prev, [id]: true }));

        // State 2: Decrypt Progress
        setDecryptSteps(prev => ({ ...prev, [id]: 'Unwrapping DEK with RSA-4096...' }));
        setDecryptProgress(prev => ({ ...prev, [id]: 50 }));
        await new Promise(r => setTimeout(r, 600));

        // State 3: Complete
        setDecryptSteps(prev => ({ ...prev, [id]: 'Decrypted with AES-256-GCM' }));
        setDecryptProgress(prev => ({ ...prev, [id]: 100 }));
        await new Promise(r => setTimeout(r, 200));

        setDecryptedIds(prev => ({ ...prev, [id]: true }));
        setDecryptingIds(prev => ({ ...prev, [id]: false }));
    };

    const resetDemo = () => {
        setGenState('idle');
        setGenLogs([]);
        setDecryptedIds({});
        setDecryptingIds({});
    };

    return (
        <div className="min-h-screen bg-background p-4 md:p-8">
            <div className="mx-auto max-w-6xl space-y-8">

                {/* Header */}
                <div className="flex items-center justify-between border-b pb-6">
                    <div>
                        <div className="flex items-center gap-4 text-sm text-muted-foreground mb-2">
                            <span>CryptoVault</span>
                            <span>/</span>
                            <span className="text-foreground font-medium">Demo</span>
                        </div>
                        <h1 className="text-3xl font-bold tracking-tight">Demo with Sample Data</h1>
                        <p className="text-muted-foreground mt-1">Test encryption/decryption with pre-generated files</p>
                    </div>
                    <div className="flex gap-2">
                        <Button variant="outline" onClick={resetDemo}>Reset Demo</Button>
                        <Badge variant="outline" className="h-9 px-4 text-sm">👤 Guest</Badge>
                    </div>
                </div>

                {/* Generator Section */}
                <Card className="border-2 border-dashed">
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2">
                            <FileText className="h-5 w-5" />
                            Generate Sample Files
                        </CardTitle>
                        <CardDescription>Creates 4 encrypted demo files with different formats</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-6">
                        <div className="grid md:grid-cols-2 gap-8">
                            <div className="space-y-4">
                                <ul className="space-y-2 text-sm text-muted-foreground">
                                    <li className="flex items-center gap-2">• confidential-report.txt</li>
                                    <li className="flex items-center gap-2">• medical-records.json</li>
                                    <li className="flex items-center gap-2">• financial-data.csv</li>
                                    <li className="flex items-center gap-2">• research-notes.md</li>
                                </ul>
                                <p className="text-xs text-muted-foreground">
                                    All files encrypted with AES-256-GCM + RSA-4096-OAEP
                                </p>
                            </div>

                            <div className="flex flex-col justify-center">
                                {genState === 'idle' ? (
                                    <Button size="lg" onClick={handleGenerate} className="w-full">
                                        Generate Samples
                                    </Button>
                                ) : (
                                    <div className="space-y-4">
                                        <div className="space-y-2">
                                            <div className="flex justify-between text-sm font-medium">
                                                <span>{genStep}</span>
                                                <span>{genProgress}%</span>
                                            </div>
                                            <Progress value={genProgress} className="h-2" />
                                        </div>
                                        <div className="h-32 bg-slate-950 rounded-md p-3 text-xs font-mono text-green-400 overflow-y-auto">
                                            {genLogs.map((log, i) => (
                                                <div key={i}>{log}</div>
                                            ))}
                                            {genState === 'generating' && <span className="animate-pulse">_</span>}
                                        </div>
                                        <Button disabled className="w-full">
                                            {genState === 'generated' ? '✓ Generated!' : '⏳ Generating...'}
                                        </Button>
                                    </div>
                                )}
                            </div>
                        </div>
                    </CardContent>
                </Card>

                {/* Keys Section (Slides in) */}
                {genState === 'generated' && (
                    <div className="animate-in slide-in-from-top-10 fade-in duration-700">
                        <Card className="bg-muted/30">
                            <CardHeader>
                                <CardTitle className="flex items-center gap-2">
                                    <Key className="h-5 w-5 text-primary" />
                                    Encryption Keys (Save These!)
                                </CardTitle>
                            </CardHeader>
                            <CardContent className="grid gap-6 md:grid-cols-2">
                                <div className="space-y-2">
                                    <div className="flex justify-between text-xs font-medium">
                                        <span>🔓 RSA-4096 Public Key</span>
                                        <Button variant="ghost" size="icon" className="h-6 w-6"><Copy className="h-3 w-3" /></Button>
                                    </div>
                                    <div className="h-24 bg-background border rounded p-2 text-[10px] font-mono text-muted-foreground overflow-hidden">
                                        -----BEGIN PUBLIC KEY-----<br />
                                        MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAve...<br />
                                        (512 bytes key data)<br />
                                        -----END PUBLIC KEY-----
                                    </div>
                                </div>
                                <div className="space-y-2">
                                    <div className="flex justify-between text-xs font-medium text-red-500">
                                        <span>🔴 RSA-4096 Private Key (CONFIDENTIAL)</span>
                                        <Button variant="ghost" size="icon" className="h-6 w-6"><Copy className="h-3 w-3" /></Button>
                                    </div>
                                    <div className="h-24 bg-red-50 dark:bg-red-950/10 border border-red-200 dark:border-red-900/50 rounded p-2 text-[10px] font-mono text-red-800 dark:text-red-400 overflow-hidden">
                                        -----BEGIN PRIVATE KEY-----<br />
                                        MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEA...<br />
                                        ⚠️ Never share this key with anyone!<br />
                                        -----END PRIVATE KEY-----
                                    </div>
                                </div>
                            </CardContent>
                        </Card>
                    </div>
                )}

                {/* Encrypted Files List (Slides up) */}
                {genState === 'generated' && (
                    <div className="space-y-4 animate-in slide-in-from-bottom-20 fade-in duration-1000 delay-300">
                        <h2 className="text-xl font-bold flex items-center gap-2">
                            <Shield className="h-5 w-5" /> Encrypted Files
                        </h2>

                        <div className="grid gap-6 md:grid-cols-2">
                            {SAMPLE_FILES.map((file) => (
                                <Card key={file.id} className={cn("transition-all duration-300", decryptedIds[file.id] ? "border-green-500/50 bg-green-50/10" : "")}>
                                    <CardHeader className="pb-3 border-b bg-muted/20">
                                        <div className="flex justify-between items-start">
                                            <div className="flex items-center gap-3">
                                                <FileIcon type={file.type} />
                                                <div>
                                                    <CardTitle className="text-base">{file.name}</CardTitle>
                                                    <CardDescription className="text-xs mt-1">
                                                        {decryptedIds[file.id] ? file.origSize : file.encSize}
                                                    </CardDescription>
                                                </div>
                                            </div>
                                            {decryptedIds[file.id] ? (
                                                <Badge className="bg-green-500 hover:bg-green-600">
                                                    <CheckCircle className="h-3 w-3 mr-1" /> Decrypted
                                                </Badge>
                                            ) : (
                                                <Badge variant="secondary">
                                                    <Lock className="h-3 w-3 mr-1" /> Encrypted
                                                </Badge>
                                            )}
                                        </div>
                                    </CardHeader>
                                    <CardContent className="pt-4 space-y-4">
                                        {/* File Info */}
                                        <div className="text-xs text-muted-foreground space-y-1">
                                            <div className="flex justify-between">
                                                <span>Type: {file.type}</span>
                                                <span>Encrypted: {file.encSize}</span>
                                            </div>
                                            <div className="flex gap-2 pt-2">
                                                <Badge variant="outline" className="text-[10px]">AES-256-GCM</Badge>
                                                <Badge variant="outline" className="text-[10px]">RSA-4096-OAEP</Badge>
                                            </div>
                                        </div>

                                        {/* Encrypted Data / Content */}
                                        {!decryptedIds[file.id] ? (
                                            <div className="space-y-4">
                                                <div className="rounded border bg-slate-950 p-3">
                                                    <div className="text-[10px] text-slate-500 mb-1 uppercase tracking-wider">Encrypted Data (Base64)</div>
                                                    <div className="text-[10px] font-mono text-slate-400 break-all line-clamp-3 leading-relaxed opacity-60">
                                                        U2FsdGVkX1+vupppZksvRf5pq5g5XjFRlipRXk...Wn9fKpZ8YhGvN3TmQx2sL9Pk4Jd8Fc7Rb...
                                                    </div>
                                                </div>

                                                {decryptingIds[file.id] ? (
                                                    <div className="space-y-2">
                                                        <div className="text-xs font-medium text-blue-500 animate-pulse">
                                                            {decryptSteps[file.id]}
                                                        </div>
                                                        <Progress value={decryptProgress[file.id]} className="h-1.5" />
                                                    </div>
                                                ) : (
                                                    <Button
                                                        className="w-full"
                                                        variant="outline"
                                                        onClick={() => handleDecrypt(file.id)}
                                                    >
                                                        <Unlock className="h-4 w-4 mr-2" />
                                                        Decrypt
                                                    </Button>
                                                )}
                                            </div>
                                        ) : (
                                            <div className="animate-in slide-in-from-top-2 fade-in duration-300">
                                                <div className="rounded-lg border bg-green-50/50 dark:bg-green-900/10 p-4 font-mono text-sm overflow-x-auto">
                                                    <div className="flex justify-between items-center mb-2 border-b border-green-200 dark:border-green-800 pb-2">
                                                        <span className="text-xs font-bold text-green-700 dark:text-green-400">📖 Decrypted Content</span>
                                                        <div className="flex gap-2">
                                                            <Button size="icon" variant="ghost" className="h-6 w-6"><Copy className="h-3 w-3" /></Button>
                                                            <Button size="icon" variant="ghost" className="h-6 w-6"><Download className="h-3 w-3" /></Button>
                                                        </div>
                                                    </div>
                                                    <pre className={cn("text-xs leading-relaxed", file.isJson ? "text-blue-600 dark:text-blue-400" : "text-foreground")}>
                                                        {file.content}
                                                    </pre>
                                                </div>
                                            </div>
                                        )}
                                    </CardContent>
                                </Card>
                            ))}
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}

function FileIcon({ type }: { type: string }) {
    if (type.includes('json')) return <FileJson className="h-8 w-8 text-orange-500" />;
    if (type.includes('csv')) return <FileType className="h-8 w-8 text-green-500" />;
    if (type.includes('markdown')) return <FileCode className="h-8 w-8 text-purple-500" />;
    return <FileText className="h-8 w-8 text-blue-500" />;
}
