/**
 * Generate sample encrypted files for demo purposes
 */

import { envelopeEncrypt } from '../crypto/envelope-encryption';
import { generateRSAKeyPair, exportRSAKeyPair } from '../crypto/rsa';

export interface SampleFile {
    name: string;
    content: string;
    mimeType: string;
}

export const sampleFiles: SampleFile[] = [
    {
        name: 'confidential-report.txt',
        content: `CONFIDENTIAL REPORT

This is a sample encrypted document demonstrating:
- AES-256-GCM encryption
- RSA-4096-OAEP key wrapping
- HMAC-SHA512 authentication
- Secure cloud storage

The content of this file is encrypted client-side before upload.
Even the cloud provider cannot read this data!

Security Features:
✓ End-to-end encryption
✓ Zero-knowledge architecture
✓ Tamper-proof audit logs
✓ Quantum-resistant options

Generated by CryptoVault Enterprise
${new Date().toISOString()}`,
        mimeType: 'text/plain',
    },
    {
        name: 'medical-records.json',
        content: JSON.stringify(
            {
                patient: {
                    id: 'PATIENT-12345',
                    name: 'John Doe',
                    dob: '1990-01-01',
                    bloodType: 'A+',
                },
                diagnosis: [
                    { date: '2025-01-01', condition: 'Hypertension', severity: 'Mild' },
                    {
                        date: '2025-06-15',
                        condition: 'Type 2 Diabetes',
                        severity: 'Controlled',
                    },
                ],
                medications: [
                    { name: 'Lisinopril', dosage: '10mg', frequency: 'Daily' },
                    { name: 'Metformin', dosage: '500mg', frequency: 'Twice daily' },
                ],
                encrypted: true,
                encryptionAlgorithm: 'AES-256-GCM',
                note: 'This sensitive medical data is protected by military-grade encryption',
            },
            null,
            2
        ),
        mimeType: 'application/json',
    },
    {
        name: 'financial-data.csv',
        content: `Date,Transaction,Amount,Category,Encrypted
2026-01-01,Salary Deposit,5000.00,Income,YES
2026-01-05,Rent Payment,-1200.00,Housing,YES
2026-01-10,Grocery Shopping,-250.50,Food,YES
2026-01-15,Investment,-1000.00,Savings,YES
2026-01-20,Utility Bills,-150.00,Bills,YES

Note: All financial records are encrypted with AES-256-GCM
Access requires valid RSA-4096 private key
Integrity verified with HMAC-SHA512`,
        mimeType: 'text/csv',
    },
    {
        name: 'research-notes.md',
        content: `# Quantum-Resistant Cryptography Research

## Abstract
This document explores post-quantum cryptographic algorithms...

## CRYSTALS-Kyber
- Lattice-based key encapsulation mechanism (KEM)
- Security level: NIST Level 3
- Key size: 1568 bytes (public key)
- Resistant to Shor's algorithm

## CRYSTALS-Dilithium
- Lattice-based digital signatures
- Signature size: ~2420 bytes
- Verification time: ~0.1ms

## Implementation Status
✓ Kyber-768 integrated
✓ Hybrid mode (RSA + Kyber)
✓ Backward compatibility maintained

---
*This research document is encrypted and stored securely*`,
        mimeType: 'text/markdown',
    },
];

/**
 * Generate encrypted sample files
 */
export async function generateEncryptedSamples(): Promise<{
    files: {
        name: string;
        encrypted: any;
        mimeType: string;
        originalSize: number;
    }[];
    keyPair: { publicKey: string; privateKey: string };
    summary: string;
}> {
    // Generate key pair for encryption
    const keyPair = await generateRSAKeyPair();
    const exportedKeys = await exportRSAKeyPair(keyPair);

    // Encrypt all sample files
    const encryptedFiles = await Promise.all(
        sampleFiles.map(async (file) => {
            const encrypted = await envelopeEncrypt(file.content, keyPair.publicKey);
            return {
                name: file.name,
                encrypted,
                mimeType: file.mimeType,
                originalSize: file.content.length,
            };
        })
    );

    const summary = `Generated ${encryptedFiles.length} sample encrypted files:
${sampleFiles.map((f) => `- ${f.name} (${f.mimeType})`).join('\n')}

All files encrypted with:
- AES-256-GCM (data encryption)
- RSA-4096-OAEP (key wrapping)
- HMAC-SHA512 (integrity)`;

    return {
        files: encryptedFiles,
        keyPair: exportedKeys,
        summary,
    };
}
